version: '3.8'
services:
  ui:
    container_name: k8s-observatory-ui
    build:
      context: ui/
      dockerfile: Dockerfile
    ports:
      - '80:3000'
  api:
    container_name: k8s-observatory-api
    build:
      context: api/
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
