name: CI - Create Release and Publish
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
    - name: Update version in pom.xml (Release only)
      run: |
        mvn -B versions:set -DnewVersion=${{ steps.gitversion.outputs.semVer }} -DgenerateBackupPoms=false -Dregistry=https://maven.pkg.github.com/dishantkamble -Dtoken=$GH_TOKEN --file api/pom.xml
        git config user.email "dishantk@gmail.com"
        git config user.name "Dishant Kamble"
        git add .
        git commit -m "Bump Version - maven"
        git push
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Build with Maven
      run: mvn -B package --file api/pom.xml install -Dtoken=$GH_TOKEN
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Publish to GitHub Packages (Maven)
      run: |
        cd api
        mvn -B deploy -Dregistry=https://maven.pkg.github.com/dishantkamble -Dtoken=$GH_TOKEN
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Comput Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3.7.0
      with:
        configuration: "changelog_config.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: ${{ steps.gitversion.outputs.semVer }}
        body: ${{ steps.changelog.outputs.changelog}}
        generateReleaseNotes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
